# Generated by Django 5.0.7 on 2024-11-16 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='variation',
            new_name='variation_category',
        ),
    ]
