# Generated by Django 5.1.3 on 2024-11-13 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EK_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
